@baseUrl = http://localhost:8080/api/v1


### [1] Create a reservation (2 passengers)
# @name createReservation
POST {{baseUrl}}/reservations?requesterId=1
Content-Type: application/json

{
  "flightId": 1,
  "externalReservationId": "EXT-B2B-00123",
  "passengers": [
    {
      "documentType": "CC",
      "documentNumber": "987654322",
      "firstName": "pasajero",
      "lastName": "3"
    },
    {
      "documentType": "PASAPORTE",
      "documentNumber": "PA-555-2027",
      "firstName": "pasajero",
      "lastName": "4"
    }
  ]
}

###

### [2] Confirm the reservation created above (once payment is confirmed)
POST {{baseUrl}}/reservations/1/confirm?requesterId=1

###

### [3] Get all reservations for flight ID 1
GET {{baseUrl}}/reservations/flight/1

###

### [4] Test — Attempt to create a reservation with no passengers (expects 400)
POST {{baseUrl}}/reservations?requesterId=1
Content-Type: application/json

{
  "flightId": 1,
  "passengers": []
}

###

### [5] Test — Attempt to fetch a reservation for a non-existent flight (expects 404)
GET {{baseUrl}}/reservations/flight/9999




### DYNAMIC SEARCH TESTS

### [A] Search all reservations (no parameters)
GET {{baseUrl}}/reservations/search

###

### [B] Search by origin only
GET {{baseUrl}}/reservations/search?origin=Bogota

###

### [C] Search by passenger document only
GET {{baseUrl}}/reservations/search?passengerDocument=987654321

###

### [D] Search by multiple fields (destination AND date)
GET {{baseUrl}}/reservations/search?destination=Medellin&date=2026-08-15

###

### [E] Search by exact flightId
GET {{baseUrl}}/reservations/search?flightId=1

